export const ACTIONS = {
    COMMON_ACTIONS: {
        SET_MENU_STATE: 'SET_MENU_STATE',
        SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
        UPDATE_FILTERS: 'UPDATE_FILTERS'
    },
    HOME_ROUTE_ACTIONS: {
        UPDATE_ROUTE: 'UPDATE_ROUTE',
        RESET_ROUTE: 'RESET_ROUTE',
        SET_SHOWBOTH: 'SET_SHOWBOTH',
        SET_ISLAST: 'SET_ISLAST',
        SET_UNSET_SPLASH_SCREEN: 'SET_UNSET_SPLASH_SCREEN',
        SET_HOME_TO_ROOT: 'SET_HOME_TO_ROOT'
    },
    USER_ACTIONS: {
        ADD_CURRENT_USER: 'ADD_CURRENT_USER',
        ADD_APPLICATION_DATA: 'ADD_APPLICATION_DATA',
        REMOVE_USER: 'REMOVE_USER',
        SET_USER_MENU_STATE: 'SET_USER_MENU_STATE'
    },
} as const