export const ACTIONS = {
    COMMON_ACTIONS: {
        SET_MENU_STATE: 'SET_MENU_STATE',
        SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    },
    HOME_ROUTE_ACTIONS: {
        UPDATE_ROUTE: 'UPDATE_ROUTE',
        SET_SHOWBOTH: 'SET_SHOWBOTH',
        SET_ISLAST: 'SET_ISLAST',
        SET_UNSET_SPLASH_SCREEN: 'SET_UNSET_SPLASH_SCREEN'
    },
    USER_ACTIONS: {
        ADD_CURRENT_USER: 'ADD_CURRENT_USER',
        ADD_APPLICATION_DATA: 'ADD_APPLICATION_DATA',
        REMOVE_USER: 'REMOVE_USER',
        SET_USER_MENU_STATE: 'SET_USER_MENU_STATE'
    },
    COURSE_ACTIONS: {
        UPDATE_COURSE_FILTERS: 'UPDATE_COURSE_FILTERS'
    }
} as const