import type { Metadata } from 'next'
import { Vollkorn } from 'next/font/google'
import './globals.css'

const vollkorn = Vollkorn({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={`h-full
      ${vollkorn.className} text-white 
      bg-neutral-dark-gray-bg`}>
        {children}
      </body>
    </html>
  )
}
